CREATE TABLE tp (id int8 generated by default as identity, name varchar(255), primary key (id));
CREATE TABLE unt (id int8 generated by default as identity, name varchar(255), primary key (id));
CREATE TABLE sensor (id int8 generated by default as identity, description varchar(255), location varchar(255), model varchar(255), range_from int4 not null, range_to int4 not null, title varchar(255), type varchar(255), unit varchar(255), primary key (id));

INSERT INTO public.tp(name)
	VALUES ('Pressure');
INSERT INTO public.tp(name)
	VALUES ('Voltage');
INSERT INTO public.tp(name)
	VALUES ('Temperature');
INSERT INTO public.tp(name)
	VALUES ('Humidity');
    INSERT INTO public.unt(name)
	VALUES ('°С');
INSERT INTO public.unt(name)
	VALUES ('bar');
INSERT INTO public.unt(name)
	VALUES ('voltage');
INSERT INTO public.unt(name)
	VALUES ('%');

INSERT INTO public.sensor(
    title, description, location, model, range_from, range_to,  type, unit)
VALUES ( 'Barometer', 'description', 'kitchen', 'ac-23', 22, 45, 'Pressure', 'bar');
INSERT INTO public.sensor(
    title, description, location, model, range_from, range_to,  type, unit)
VALUES ( 'Moisture Meter', 'description', 'livingroom', 'bf-19', 5, 45, 'Humidity', '%');
INSERT INTO public.sensor(
    title, description, location, model, range_from, range_to,  type, unit)
VALUES ( 'Temperature Sensor', 'description', 'livingroom', 'ac-19', -23, 65, 'Temperature', '°С');
